### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Mudit018**

### CODE REVIEW

**Comment by garvitchittora** [comment]
@Mudit018 Great 👍

**Comment by infern018** [comment]
@Mudit018  attach a ss of the navbar

**Comment by garvitchittora** [comment]
@infern018  https://mudit018.github.io/Asmita-Header-Footer/

**Review by infern018 — APPROVED** [review]
lgtm

**Review by zorione — COMMENTED** [review]
@garvitchittora Font yahi rakhna hai ?

**Pull request merged**
